---
homelab:
  hosts:
    cocoa.home.arpa:
      ansible_host: 192.168.0.3
      ansible_port: 22
      ansible_user: root
    nutmeg.home.arpa:
      ansible_host: 192.168.0.4
      ansible_port: 22
      ansible_user: root
demo:
  hosts:
    advprog:
      ansible_host: csui-advprog.backtruck.art
      ansible_port: 22
      ansible_user: root
