---
- name: Set up administrator user and minimum system packages
  hosts: homelab
  vars_prompt:
    - name: user_username
      prompt: Provide username for the default, non-root administrator user
      private: false
    - name: user_password
      prompt: Provide password for the default, non-root adminstrator user
      private: true
      encrypt: sha512_crypt
      confirm: true
  roles:
    - role: common
    - role: user
