---
- name: Install system packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - gpg
      - gpg-agent
      - python3-apt
      - python3-pip
      - python3-setuptools
      - software-properties-common
    state: present
    install_recommends: no

- name: Install Python packages
  ansible.builtin.pip:
    name:
      - passlib
    state: present
